src/app/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the Closure to execute when that URI is requested.
|
*/

Route::group(array('before' => 'auth'), function()
{
    Route::get('/', array(
        'as' => 'all_notes', 'uses' => 'NoteController@index'
        )
    );

    # user related routes (authed)
    Route::get('settings', array(
        'as' => 'settings', 'uses' => 'UserController@settings'
        )
    );
    Route::post('settings', array(
        'as' => 'settings.update', 'uses' => 'UserController@updateSettings'
        )
    );
    Route::get('signout', array('as' => 'signout', function() {
        Auth::logout();
        return Redirect::route('signin');
    }));

    # customized pad resource controller
    Route::post('pads/{id}/update', array(
        'as' => 'pads.update', 'uses' => 'PadController@update'
        )
    );
    Route::get('pads/{id}/delete', array(
        'as' => 'pads.delete', 'uses' => 'PadController@delete'
        )
    );
    Route::post('pads/{id}/delete', array(
        'as' => 'pads.destroy', 'uses' => 'PadController@destroy'
        )
    );
    Route::resource('pads', 'PadController',
        array('except' => array('destroy', 'index', 'update')));

    # customized note resource controller
    Route::post('notes/{id}/update', array(
        'as' => 'notes.update', 'uses' => 'NoteController@update'
        )
    );
    Route::get('notes/{id}/delete', array(
        'as' => 'notes.delete', 'uses' => 'NoteController@delete'
        )
    );
    Route::post('notes/{id}/delete', array(
        'as' => 'notes.destroy', 'uses' => 'NoteController@destroy'
        )
    );
    Route::resource('notes', 'NoteController',
        array('except' => array('destroy', 'index', 'update')));
});

# user related routes (anonymous)
Route::get(
    'signup',
    array('as' => 'signup', 'uses' => 'UserController@signup')
);
Route::post(
    'signup',
    array('as' => 'user.store', 'uses' => 'UserController@store')
);

Route::get(
    'signin',
    array('as' => 'signin', 'uses' => 'UserController@signin')
);
Route::post(
    'signin',
    array('as' => 'signin.process', 'uses' => 'UserController@processSignin')
);
Route::match(
    array('GET', 'POST'),
    'forgot-password',
    array('as' => 'forgot_password', 'uses' => 'UserController@forgotPassword')
);

Route::get(
    'healthcheck',
    function() {
        return Response::make('OK', 200);
    }
);

src/app/models/Pad.php
<?php

use Illuminate\Auth\UserInterface;

class Pad extends Eloquent {

    /**
     * The database table used by the model.
     *
     * @var string
     */
    protected $table = 'pads';

    protected $fillable = array('name');

    public function user()
    {
        return $this->belongsTo('User');
    }

    public function notes()
    {
        return $this->hasMany('Note');
    }
}

src/app/controllers/PadController.php
<?php

class PadController extends BaseController {

    public function create()
    {
        return View::make('pad/create');
    }

    public function store()
    {
        $validation = $this->validator();
        if ($validation->fails())
        {
            return Redirect::route('pads.create')->withErrors($validation);
        }
        $pad = new Pad(array('name' => Input::get('name')));
        Auth::user()->pads()->save($pad);
        return Redirect::route('pads.show', array('id' => $pad->id))
            ->with('success', 'Pad is created.');
    }

    public function edit($id)
    {
        $pad = $this->getPadOrFail($id);
        return View::make('pad/edit', array('pad' => $pad));
    }

    public function update($id)
    {
        $pad = $this->getPadOrFail($id);
        $validation = $this->validator();
        if ($validation->fails())
        {
            return Redirect::route('pads.edit', array('id' => $pad->id))
                ->withErrors($validation);
        }
        $pad->name = Input::get('name');
        $pad->save();
        return Redirect::route('pads.show', array('id' => $pad->id))
            ->with('success', 'Pad is updated.');
    }

    public function show($id)
    {
        $pad = $this->getPadOrFail($id);
        $orderParams = $this->processOrderParam();
        $notes = $pad->notes()->orderBy(
            $orderParams[0], $orderParams[1]
        )->get();
        return View::make(
            'pad/view',
            array('pad' => $pad, 'notes' => $notes)
        );
    }

    public function delete($id)
    {
        $pad = $this->getPadOrFail($id);
        return View::make('pad/delete', array('pad' => $pad));
    }

    public function destroy($id)
    {
        $pad = $this->getPadOrFail($id);
        $pad->delete();
        return Redirect::route('all_notes')
            ->with('success', 'Pad is deleted.');
    }

    private function getPadOrFail($id)
    {
        return Auth::user()->pads()
            ->where('id', '=', $id)->firstOrFail();
    }

    private function validator()
    {
        return Validator::make(
            Input::all(),
            array(
                'name' => 'required',
            )
        );
    }
}

src/app/views/pad/create.blade.php
@extends('user')

@section('page_title')
New pad
@stop

@section('content')
    {{ Form::open(array('route' => 'pads.store')) }}

    {{ Form::label('name', 'Name') . Form::text('name', Input::old('name')) }}
    @include('partials.error', array('error' => $errors->first('name')))

    {{ Form::submit('Save') }}

    {{ Form::close() }}

@stop

src/app/views/pad/delete.blade.php
@extends('user')

@section('page_title')
Delete pad {{ $pad->name }}
@stop

@section('content')
    {{ Form::open(array('route' => array('pads.destroy', $pad->id))) }}
    <p>Are you sure you want to delete {{ $pad->name }}?</p>
    {{ Form::submit('Yes, I want to delete this pad', array('class' => 'button red')) }}
    <a href="{{ URL::route('pads.edit', array('id' => $pad->id))}}">Cancel</a>

    {{ Form::close() }}
@stop

src/app/views/pad/edit.blade.php
@extends('user')

@section('page_title')
{{ $pad->name }}
@stop

@section('content')
    {{ Form::open(array('route' => array('pads.update', $pad->id))) }}

    {{ Form::label('name', 'Name') . Form::text('name', $pad->name) }}
    @include('partials.error', array('error' => $errors->first('name')))

    {{ Form::submit('Save') }}
    {{ Form::close() }}
    <a class="red" href="{{ URL::route('pads.delete', array('id' => $pad->id)) }}">Delete pad</a>

@stop

src/app/views/pad/view.blade.php
@extends('user')

@section('page_title')
{{ $pad->name; }} ({{ $notes->count() }})
@stop

@section('content')
    @if ($notes->count())
        <table class="notes">
            <tr>
                <th class="note">Note <a href="{{ URL::route('pads.show', array('id' => $pad->id)) }}?order=-name" class="sort_arrow" >&uarr;</a><a href="{{ URL::route('pads.show', array('id' => $pad->id)) }}?order=name" class="sort_arrow" >&darr;</a></th>
                <th class="date">Last modified <a href="{{ URL::route('pads.show', array('id' => $pad->id)) }}?order=-updated_at" class="sort_arrow" >&uarr;</a><a href="{{ URL::route('pads.show', array('id' => $pad->id)) }}?order=updated_at" class="sort_arrow" >&darr;</a></th>
            </tr>
            @foreach ($notes as $note)
                <tr>
                    <td><a href="{{ URL::route('notes.show', array('id' => $note->id)) }}">{{ $note->name }}</a></td>
                    <td class="hidden-text date">{{ $note->smartDate(); }}</td>
                </tr>
            @endforeach
        </table>
    @else
        <p class="empty">You don't have notes in this pad yet.</p>
    @endif
    <a href="{{ URL::route('notes.create') }}?pad={{ $pad->id; }}" class="button">New note</a>&nbsp;
    <a href="{{ URL::route('pads.edit', array('id' => $pad->id)) }}">Pad settings</a>
@stop