src/app/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the Closure to execute when that URI is requested.
|
*/

Route::group(array('before' => 'auth'), function()
{
    Route::get('/', array(
        'as' => 'all_notes', 'uses' => 'NoteController@index'
        )
    );

    # user related routes (authed)
    Route::get('settings', array(
        'as' => 'settings', 'uses' => 'UserController@settings'
        )
    );
    Route::post('settings', array(
        'as' => 'settings.update', 'uses' => 'UserController@updateSettings'
        )
    );
    Route::get('signout', array('as' => 'signout', function() {
        Auth::logout();
        return Redirect::route('signin');
    }));

    # customized pad resource controller
    Route::post('pads/{id}/update', array(
        'as' => 'pads.update', 'uses' => 'PadController@update'
        )
    );
    Route::get('pads/{id}/delete', array(
        'as' => 'pads.delete', 'uses' => 'PadController@delete'
        )
    );
    Route::post('pads/{id}/delete', array(
        'as' => 'pads.destroy', 'uses' => 'PadController@destroy'
        )
    );
    Route::resource('pads', 'PadController',
        array('except' => array('destroy', 'index', 'update')));

    # customized note resource controller
    Route::post('notes/{id}/update', array(
        'as' => 'notes.update', 'uses' => 'NoteController@update'
        )
    );
    Route::get('notes/{id}/delete', array(
        'as' => 'notes.delete', 'uses' => 'NoteController@delete'
        )
    );
    Route::post('notes/{id}/delete', array(
        'as' => 'notes.destroy', 'uses' => 'NoteController@destroy'
        )
    );
    Route::resource('notes', 'NoteController',
        array('except' => array('destroy', 'index', 'update')));
});

# user related routes (anonymous)
Route::get(
    'signup',
    array('as' => 'signup', 'uses' => 'UserController@signup')
);
Route::post(
    'signup',
    array('as' => 'user.store', 'uses' => 'UserController@store')
);

Route::get(
    'signin',
    array('as' => 'signin', 'uses' => 'UserController@signin')
);
Route::post(
    'signin',
    array('as' => 'signin.process', 'uses' => 'UserController@processSignin')
);
Route::match(
    array('GET', 'POST'),
    'forgot-password',
    array('as' => 'forgot_password', 'uses' => 'UserController@forgotPassword')
);

Route::get(
    'healthcheck',
    function() {
        return Response::make('OK', 200);
    }
);

src/app/views/layout.blade.php
<!DOCTYPE html>
<!--[if lt IE 7 ]><html class="ie ie6" lang="en"> <![endif]-->
<!--[if IE 7 ]><html class="ie ie7" lang="en"> <![endif]-->
<!--[if IE 8 ]><html class="ie ie8" lang="en"> <![endif]-->
<!--[if (gte IE 9)|!(IE)]><!--><html lang="en"> <!--<![endif]-->
<head>

	<!-- Basic Page Needs
  ================================================== -->
	<meta charset="utf-8">
	<title>@yield('page_title')</title>
	<meta name="description" content="">
	<meta name="author" content="">

	<!-- Mobile Specific Metas
  ================================================== -->
	<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">

	<!-- CSS
  ================================================== -->
    {{ HTML::style('https://cdnjs.cloudflare.com/ajax/libs/skeleton/1.2/base.min.css') }}
    {{ HTML::style('https://cdnjs.cloudflare.com/ajax/libs/skeleton/1.2/skeleton.min.css') }}
    {{ HTML::style('https://cdnjs.cloudflare.com/ajax/libs/skeleton/1.2/layout.css') }}
    {{ HTML::style('css/style.css') }}

	<!--[if lt IE 9]>
		<script src="https://html5shim.googlecode.com/svn/trunk/html5.js"></script>
	<![endif]-->
</head>
<body>
	<div class="container">
        <div class="sixteen columns">
            <div class="sign-in-out-block">
                @if(Auth::check())
                    {{ Auth::user()->email }}:&nbsp; <a href="{{ URL::route('settings'); }}">Account Settings</a> &nbsp;&nbsp;&nbsp;<a href="{{ URL::route('signout'); }}">Sign out</a>
                @else
                    <a href="{{ URL::route('signup'); }}">Sign up</a>&nbsp;&nbsp;&nbsp;<a href="{{ URL::route('signin'); }}">Sign in</a>
                @endif
            </div>
        </div>
        <div class="sixteen columns">
            <h1 class="bold-header">
                <a href="{{ URL::route('all_notes'); }}" class="header">note<span class="jam">jam: </span></a>
                <span>@yield('page_title')</span>
            </h1>
        </div>
        @yield('pads')
        <div class="@yield('content_class', 'sixteen') columns content-area">
            @if(Session::has('success') || Session::has('error'))
            <div class="alert-area">
                @if(Session::has('success'))
                    <div class="alert alert-success">{{ Session::get('success') }}</div>
                    {{ Session::forget('success') }}
                @endif
                @if(Session::has('error'))
                    <div class="alert alert-error">{{ Session::get('error') }}</div>
                    {{ Session::forget('error') }}
                @endif
            </div>
            @endif
            @yield('content')
        </div>
        <hr class="footer" />
        <div class="footer">
            <div>Notejam: <strong>Laravel</strong> application</div>
            <div><a href="https://github.com/komarserjio/notejam">Github</a>, <a href="https://twitter.com/komarserjio">Twitter</a>, created by <a href="https://github.com/komarserjio/">Serhii Komar</a></div>
        </div>
	</div><!-- container -->
    <a href="https://github.com/you"><img style="position: absolute; top: 0; right: 0; border: 0;" src="https://s3.amazonaws.com/github/ribbons/forkme_right_gray_6d6d6d.png" alt="Fork me on GitHub"></a>
</body>
</html>

src/app/views/user.blade.php
@extends('layout')

@section('content_class')
thirteen
@stop

@section('pads')
    <div class="three columns">
        <h4 id="logo">My pads</h4>
        <nav>
            @if(Auth::user()->pads->count())
                <ul>
                @foreach(Auth::user()->pads as $pad)
                    <li><a href="{{ URL::route('pads.show', array('id' => $pad->id) )}}">{{ $pad->name; }}</a></li>
                @endforeach
                </ul>
            @else
                <p class="empty">No pads</p>
            @endif
            <hr />
            <a href="{{ URL::route('pads.create'); }}">New pad</a>
        </nav>
    </div>
@stop